using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CustomersApi.Models
{
    public class Accounts
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // Specifies that the primary key value is provided by the application, not generated by the database.
        public long AccountID { get; set; }
         
        [Column(TypeName = "money")]
        public decimal Balance { get; set; }

        [Required]
        public bool HasCheque { get; set; }

        [Required]
        public int WdQuota { get; set; } // Withdrawal quota

        [Required]
        public int DpQuota { get; set; } // Deposit quota

        [Required]
        public bool IsActive { get; set; }

        [ForeignKey("Customer")]
        public int CustomerID { get; set; }

        public int TypeId { get; set; }

    
        [StringLength(11)]
        public string BranchID { get; set; }

        // Navigation properties to related tables
        public virtual Customer Customer { get; set; }
        //public virtual AccountType AccountType { get; set; }
       // public virtual Branch Branch { get; set; }
    }

}
